web/cctvweb/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from django.http import HttpResponseRedirect
import clips

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'cctvweb.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),
    url(r'^clips/', include('clips.urls')),
    url(r'^$', lambda r: HttpResponseRedirect('clips/')),
    url(r'^admin/', include(admin.site.urls)),
)

web/clips/urls.py
from django.conf.urls import patterns, url

import views

urlpatterns = patterns('',
    url(r'^$', views.index, name='home'),
    url(r'^list/?$', views.list, name='list'),
    url(r'^watch/?$', views.watch, name='watch'),
    url(r'^camera/(?P<camera_name>.+)/?$', views.camera, name='camera')
#    url(r'^(?P<clip_id>\d+)/$', views.detail, name='detail'),
)

web/clips/models.py
from django.db import models
from django import forms
from mongoengine import *
from cctvweb.settings import DBNAME
from datetimewidget.widgets import DateTimeWidget

import models

connect(DBNAME)

class logmsg(DynamicDocument):
    message = StringField()
    level = StringField()

class clip(DynamicDocument):
    data = FileField()
    save_time = DateTimeField()
    start_frame_index = LongField() 
    start_time = DateTimeField() 
    end_time = DateTimeField() 
    module_name = StringField() 
    end_frame_index = LongField() 
    camera_name = StringField()

class analysis(DynamicDocument):
    pass

class ClipForm(forms.Form):
    start_datetime = forms.DateTimeField(widget=DateTimeWidget(usel10n=True, bootstrap_version=3, attrs={'label': "Start", "readonly": ''}))
    end_datetime = forms.DateTimeField(widget=DateTimeWidget(usel10n=True, bootstrap_version=3, attrs={'label': "End", "readonly": ''}))
    camera_name = forms.Field()

web/clips/views.py
import os
import logging

from datetime import datetime, timedelta

from django.shortcuts import render
from django.core.paginator import Paginator
from django.template import RequestContext, loader
from django.http import HttpResponse

from graphos.sources.simple import SimpleDataSource
from graphos.renderers import flot

import models
import tools

# --- view methods ---
def index(request):
    return render(request, 'clips/index.html', {"logs": models.logmsg.objects.order_by('-save_time').limit(50)})

def watch(request):
    error = "An unrecognised error occured whilst loading the video!"
    if request.method == 'POST':
        form = models.ClipForm(request.POST)
    else:
        print(datetime.fromtimestamp(float(request.GET['start_datetime'])))
        start_datetime = float(request.GET['start_datetime'])
        end_datetime = float(request.GET['end_datetime'])
        if start_datetime < 0:
            start_datetime = end_datetime + start_datetime
        form = models.ClipForm({"start_datetime":   datetime.fromtimestamp(start_datetime),
                                "end_datetime":     datetime.fromtimestamp(end_datetime),
                                "camera_name":      request.GET['camera_name']})

    if form.is_valid(): # All validation rules pass
        from itertools import chain
        # retrieve all clips between the entered datetimes
        # allow 15 seconds either side to ensure the datetimes
        # requested are included in the video
        clips = models.clip.objects.filter(camera_name=form.cleaned_data['camera_name']).filter(start_time__gte=form.cleaned_data['start_datetime']-timedelta(seconds=15), end_time__lte=form.cleaned_data['end_datetime']+timedelta(seconds=15)).order_by('start_time')

        datetime_segments = tools.find_datetime_segments(clips)
        if len(datetime_segments) > 0:
            mp4_file = tools.wrap_h264([c.data for c in clips])
            start_datetime = None
            c = None
            for c in clips:
                if start_datetime is None:
                    start_datetime = c.start_time
            end_datetime = c.end_time
            if mp4_file:
                camera_list = models.clip.objects.distinct("camera_name")
                return render(request, 'clips/watch.html', {"clip_url": "http://cctv.lan/stream/%s" % os.path.basename(mp4_file.name),
                                                            "camera_name": form.cleaned_data['camera_name'],
                                                            "cameras": camera_list,
                                                            "search_form": models.ClipForm(),
                                                            "start_datetime": start_datetime,
                                                            "end_datetime": end_datetime,
                                                            "datetime_segments": datetime_segments,
                                                            "motion_data": tools.generate_motion_graph(form.cleaned_data['camera_name'], datetime_segments)})
            else:
                error = "Error creating MP4 file from chunks..."
        else:
            error = "No clips found..."
    else:
        error = "Invalid form entry..."

    return render(request, "clips/error.html", {"error": error})
    
def list(request):
    camera_list = models.clip.objects.distinct("camera_name")
    unsorted_events = map(tools.get_recent_events, camera_list)
    events_list = sorted([j for i in unsorted_events for j in i], key=lambda x: x['end_time'], reverse=True)

    return render(request, 'clips/list.html', {"cameras": camera_list,
                                               "search_form": models.ClipForm(),
                                               "events_list": events_list,
                                               })

def camera(request, camera_name):
    camera_list = models.clip.objects.distinct("camera_name")
    unsorted_events = tools.get_recent_events(camera_name)
    events_list = sorted(unsorted_events, key=lambda x: x['end_time'], reverse=True)
    now = datetime.now()
    start_datetime = now-timedelta(seconds=45)
    end_datetime = now
    clips = models.clip.objects.filter(camera_name=camera_name).filter(start_time__gte=start_datetime, end_time__lte=end_datetime).order_by('start_time')
    mp4_file = tools.wrap_h264([c.data for c in clips])
    _start_datetime = None
    c = None
    for c in clips:
        if _start_datetime is None:
            _start_datetime = c.start_time
    start_datetime = _start_datetime
    end_datetime = c.end_time
    return render(request, 'clips/camera.html', {"cameras": camera_list,
                                                 "clip_url": "http://cctv.phlat493/stream/%s" % os.path.basename(mp4_file.name),
                                                 "search_form": models.ClipForm(),
                                                 "recent_motion_chart": tools.generate_motion_graph(camera_name, [(now-timedelta(minutes=15),now)]),
                                                 "events_list": events_list,
                                                 "camera_name": camera_name,
                                                 "start_datetime": start_datetime,
                                                 "end_datetime": end_datetime, })

web/clips/templates/clips/analysis.html
{% extends 'clips/base.html' %}

{% block title %}PiCCTV{% endblock %}

{% block content %}
    <table class="table table-striped table-hover">
        <thead>
            <tr>
                <th>Module</th>
                <th>Camera</th>
            </tr>
        </thead>
        <tbody>
{% for d in data %}            
            <tr>
                <td>{{ d.module_name }}</td>
                <td>{{ d.camera_name }}</td>
            </tr>
{% endfor %}
        </tbody>
    </table>
{% endblock %}

web/clips/templates/clips/base.html
{% extends 'clips/bootstrap.html' %}

{% load url from future %}

{% load bootstrap3 %}

{% block bootstrap3_title %}PiCCTV{% endblock %}

{% block header_message %}
  <div class="spacer">

  </div>
{% endblock %}

{% block bootstrap3_content %}

{% bootstrap_messages %}

{% block content %}(no content){% endblock %}

{% endblock %}

web/clips/templates/clips/bootstrap.html
<!DOCTYPE html>
{% load bootstrap3 %}
{% load staticfiles %}
{% load base_extra %}
<html{% if request.LANGUAGE_CODE %} lang="{{ request.LANGUAGE_CODE }}"{% endif %}>

<head>
  <meta charset="utf-8">
  <!--[if IE]><meta http-equiv="X-UA-Compatible" content="IE=edge" /><![endif]-->
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>{% block bootstrap3_title %}django-bootstrap3 template title{% endblock %}</title>
  {% bootstrap_css %}
  <link href="{% static "clips/custom.css" %}" media="all" rel="stylesheet">
  <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
  <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
  <!--[if lt IE 9]>
  <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
  <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
  <![endif]-->
  {% bootstrap_javascript jquery=True %}
  {% block bootstrap3_extra_head %}{% endblock %}
</head>

<body>
  <nav class="navbar navbar-fixed-top navbar-inverse">
    <div class="container-fluid">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#clips-navbar-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="{% url 'home' %}"><span class="glyphicon glyphicon-camera" aria-hidden="true"></span> PiCCTV</a>
      </div>
      <div class="collapse navbar-collapse" id="clips-navbar-collapse">
        <ul class="nav navbar-nav">
          <li class="{% active_page request "home" %}"><a href="{% url 'home' %}">home</a></li>
          <li class="{% active_page request "list" %}"><a href="{% url 'list' %}">view clips</a></li>
        </ul>
        <div class="btn-group pull-right">
          <a href="https://git.e720.co.uk/munnerz/picctv" type="button" class="hidden-xs btn btn-default navbar-btn">Git</a>
          <a href="https://git.e720.co.uk/munnerz/picctv/issues" type="button" class="hidden-xs btn btn-danger navbar-btn">Report issue</a>
        </div>
      </div>
    </div>
  </nav>

  {% block header_message %}{% endblock %}
  {% block bootstrap3_content %}django-bootstrap3 template content{% endblock %}
  {% block bootstrap3_extra_script %}{% endblock %}
</body>

</html>

web/clips/templates/clips/camera.html
{% extends 'clips/base.html' %}

{% load base_extra %}
{% load bootstrap3 %}
{% load humanize %}
{% load static %}

{% block title %}Clip list{% endblock %}

{% block bootstrap3_extra_head %}
{{ search_form.media }}
<script src="{% static 'clips/jquery.flot.min.js' %}"></script>
{{ search_form.media }}
{% endblock %}

{% block content %}

  <div class="col-xs-12 col-sm-offset-1 col-sm-10">
    <div class="row">
      <form id="clip-form" action="{% url 'watch' %}" method="POST">
        {% csrf_token %}
        <div class="col-xs-12 col-sm-5">
          {{ search_form.start_datetime }}
        </div>

        <div class="col-xs-12 col-sm-5">
          {{ search_form.end_datetime }}
        </div>

        <input type="hidden" id="id_camera_name" name="camera_name" />

        <div class="col-xs-12 col-sm-2">
          <div class="btn-group pull-right">
            <button type="button" class="btn btn-success dropdown-toggle" data-toggle="dropdown">
              Watch <span class="caret"></span>
            </button>
            <ul class="dropdown-menu" role="menu">
{% for c in cameras %}      
              <li onclick="$('#id_camera_name').val('{{ c }}'); $('#clip-form').submit()">
                <a href="#">{{ c }}</a>
              </li>
{% endfor %}
            </ul>
          </div>
        </div>

      </form>
    </div>

    <div class="spacer row">
     <div class="col-xs-12 col-sm-3">
        <div class="panel panel-default">
          <div class="panel-heading">
            <h3 class="panel-title">Cameras</h3>
          </div>
          <div class="panel-body">
            <ul class="nav nav-pills nav-stacked">
{% for c in cameras %}
              <li role="presentation" class="{% if c == camera_name %}active{% endif %}"><a href="{% url 'camera' camera_name=c %}">{{ c }}</a></li>
{% endfor %}
            </ul>
          </div>
        </div>
      </div>
      <div class="col-xs-12 col-sm-9 pull-right">
        <row>
          <div class="panel panel-default">
            <div class="panel-body">
              <div class="embed-responsive embed-responsive-16by9">
                <video width="1280" height="720" controls>
                  <source src="{{ clip_url }}" type="video/mp4" />
                    Your browser does not support the video tag.
                </video>
              </div>
              <span class="pull-left"><a href="{% url 'watch' %}?start_datetime=-300&end_datetime={{start_datetime|epoch}}&camera_name={{camera_name}}">Previous 5 minutes</a></span>
              <span class="pull-right"><a href="{% url 'watch' %}?start_datetime={{end_datetime|epoch}}&end_datetime={{end_datetime|epoch|add:"300"}}&camera_name={{camera_name}}">Next 5 minutes</a></span>
            </div>
          </div>
        </row>
        <row>
          <div class="panel panel-default">
            <div class="panel-heading">
              <h3 class="panel-title">Last 15 minutes of motion</h3>
            </div>
            <div class="panel-body">              
              {{ recent_motion_chart.as_html }}
            </div>
          </div>
        </row>
        <div class="panel panel-default">
          <div class="panel-heading">
            <h3 class="panel-title">Recent events</h3>
          </div>
          <div class="panel-body">
            This table shows the last 200 logged events from each camera - continous modules (like Recording) be shown near the top.
          </div>
          <!-- Table -->
          <table class="table">
            <thead>
              <tr>
                <th>When</th>
                <th>Camera</th>
                <th>Module</th>
                <th>Message</th>
                <th>View</th>
              </tr>
            </thead>
{% for e in events_list %}
            <tr>
              <td>{{ e.start_time|date }} {{ e.start_time|time }} - {{ e.end_time|time }}</td>
              <td>{{ e.camera_name }}</td>
              <td>{{ e.module_name }}</td>
              <td>Triggered for {{ e.length|naturaltime }}</td>
              <td><a href="{% url 'watch' %}?start_datetime={{e.start_time|epoch}}&end_datetime={{e.end_time|epoch}}&camera_name={{e.camera_name}}">View clip</a></td>
            </tr>
{% endfor %}
          </table>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

web/clips/templates/clips/detail.html
{% extends 'clips/base.html' %}

{% block title %}django-bootstrap3{% endblock %}

{% block content %}
    Listing info for clip #{{ clip_id }}
{% endblock %}

web/clips/templates/clips/error.html
{% extends 'clips/base.html' %}

{% load base_extra %}

{% block title %}Error{% endblock %}


{% block content %}
  <div class="col-xs-10 col-xs-offset-1">
    <div class="panel panel-danger">
      <div class="panel-heading">
        <h4>{{ error }}</h4>
      </div>
    </div>
  </div>
{% endblock %}

web/clips/templates/clips/index.html
{% extends 'clips/base.html' %}

{% block nosidebar %}{% endblock %}
{% block title %}PiCCTV{% endblock %}

{% block content %}
<div class="well col-xs-12 col-sm-offset-1 col-sm-10">
        <div class="page-header">
          <h1>Recent log messages</h1>
        </div>
        <ul class="list-group">
{% for log in logs %} 
          <li class="list-group-item list-group-item-{{ log.level }}">
            
            <div id="log-meta-items" class="row visible-xs-block visible-sm-inline visible-md-inline visible-lg-inline pull-left-xs pull-right-sm">
              <button class="btn btn-xs btn-info">{{ log.save_time | date:'Y-m-d H:i:s' }}</button>
              <button class="btn btn-xs btn-{{ log.level }}">{{ log.level }}</button>
              <button class="btn btn-xs btn-success">{{ log.sender }}</button>
            </div>
            <div class="visible-xs-block clearfix"></div>
            <strong style="margin-left: 10px;">{{ log.message }}</strong>
          </li>
{% endfor %}
        </ul>
</div>
{% endblock %}

web/clips/templates/clips/list.html
{% extends 'clips/base.html' %}

{% load base_extra %}
{% load bootstrap3 %}
{% load humanize %}

{% block title %}Clip list{% endblock %}

{% block bootstrap3_extra_head %}{{ search_form.media }}{% endblock %}

{% block content %}

  <div class="col-xs-12 col-sm-offset-1 col-sm-10">
    
    <div class="row">
      <form id="clip-form" action="{% url 'watch' %}" method="POST">
        {% csrf_token %}
        <div class="col-xs-12 col-sm-5">
          {{ search_form.start_datetime }}
        </div>

        <div class="col-xs-12 col-sm-5">
          {{ search_form.end_datetime }}
        </div>

        <input type="hidden" id="id_camera_name" name="camera_name" />

        <div class="col-xs-12 col-sm-2">
          <div class="btn-group pull-right">
            <button type="button" class="btn btn-success dropdown-toggle" data-toggle="dropdown">
              Watch <span class="caret"></span>
            </button>
            <ul class="dropdown-menu" role="menu">
{% for c in cameras %}      
              <li onclick="$('#id_camera_name').val('{{ c }}'); $('#clip-form').submit()">
                <a href="#">{{ c }}</a>
              </li>
{% endfor %}
            </ul>
          </div>
        </div>

      </form>
    </div>

    <div class="spacer row">
      <div class="col-xs-12 col-sm-3">
        <div class="panel panel-default">
          <div class="panel-heading">
            <h3 class="panel-title">Cameras</h3>
          </div>
          <div class="panel-body">
            <ul class="nav nav-pills nav-stacked">
{% for c in cameras %}
              <li role="presentation"><a href="{% url 'camera' camera_name=c %}">{{ c }}</a></li>
{% endfor %}
            </ul>
          </div>
        </div>
      </div>
      <div class="col-xs-12 col-sm-9 pull-right">
        <div class="panel panel-default">
          <div class="panel-heading">
            <h3 class="panel-title">Recent events</h3>
          </div>
          <div class="panel-body">
            This table shows the last 200 logged events from each camera - continous modules (like Recording) be shown near the top.
          </div>
          <!-- Table -->
          <table class="table">
            <thead>
              <tr>
                <th>When</th>
                <th>Camera</th>
                <th>Module</th>
                <th>Message</th>
                <th>View</th>
              </tr>
            </thead>
{% for e in events_list %}
            <tr>
              <td>{{ e.start_time|date }} {{ e.start_time|time }} - {{ e.end_time|time }}</td>
              <td>{{ e.camera_name }}</td>
              <td>{{ e.module_name }}</td>
              <td>Triggered for {{ e.length|naturaltime }}</td>
              <td><a href="{% url 'watch' %}?start_datetime={{e.start_time|epoch}}&end_datetime={{e.end_time|epoch}}&camera_name={{e.camera_name}}">View clip</a></td>
            </tr>
{% endfor %}
          </table>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

web/clips/templates/clips/watch.html
{% extends 'clips/base.html' %}

{% load base_extra %}
{% load static %}

{% block title %}Clip list{% endblock %}

{% block bootstrap3_extra_head %}
<script src="{% static 'clips/jquery.flot.min.js' %}"></script>
{{ search_form.media }}
{% endblock %}

{% block content %}

  <div class="col-xs-12 col-sm-offset-1 col-sm-10">

    <div class="row">
      <form id="clip-form" action="{% url 'watch' %}" method="POST">
        {% csrf_token %}
        <div class="col-xs-12 col-sm-5">
          {{ search_form.start_datetime }}
        </div>

        <div class="col-xs-12 col-sm-5">
          {{ search_form.end_datetime }}
        </div>

        <input type="hidden" id="id_camera_name" name="camera_name" />

        <div class="col-xs-12 col-sm-2">
          <div class="btn-group pull-right">
            <button type="button" class="btn btn-success dropdown-toggle" data-toggle="dropdown">
              Watch <span class="caret"></span>
            </button>
            <ul class="dropdown-menu" role="menu">
{% for c in cameras %}      
              <li onclick="$('#id_camera_name').val('{{ c }}'); $('#clip-form').submit()">
                <a href="#">{{ c }}</a>
              </li>
{% endfor %}
            </ul>
          </div>
        </div>

      </form>
    </div>

    <div class="spacer row">

      <div class="col-xs-12 col-sm-3">
        <div class="panel panel-default">
          <div class="panel-heading">
            <h3 class="panel-title">Cameras</h3>
          </div>
          <div class="panel-body">
            <ul class="nav nav-pills nav-stacked">
{% for c in cameras %}
              <li role="presentation" class="{% if c == camera_name %}active{% endif %}"><a href="{% url 'camera' camera_name=c %}">{{ c }}</a></li>
{% endfor %}
            </ul>
          </div>
        </div>
      </div>
      <div class="col-xs-12 col-sm-9 pull-right">
        <div class="panel panel-default">
          <div class="panel-body">
            <div class="embed-responsive embed-responsive-16by9">
              <video width="1280" height="720" controls>
                <source src="{{ clip_url }}" type="video/mp4">
              Your browser does not support the video tag.
              </video>
            </div>
            <span class="pull-left"><a href="{% url 'watch' %}?start_datetime=-300&end_datetime={{start_datetime|epoch}}&camera_name={{camera_name}}">Previous 5 minutes</a></span>
            <span class="pull-right"><a href="{% url 'watch' %}?start_datetime={{end_datetime|epoch}}&end_datetime={{end_datetime|epoch|add:"300"}}&camera_name={{camera_name}}">Next 5 minutes</a></span>
          </div>
        </div>
      </div>

      <div class="col-xs-12 col-sm-9 pull-right">
        <div class="panel panel-default">
          <div class="panel-heading">
            <h3 class="panel-title">Clip info</h3>
          </div>
          <div class="panel-body">
            <ul>
  {% for start,end in datetime_segments %}
            <li>{{ start|date:"dS M Y H:i:s" }} - {{ end|date:"d/m/Y H:i:s" }}</li>
  {% endfor %}
            </ul>
            
            {{ motion_data.as_html }}
          </div>
        </div>
      </div>

    </div>

  </div>
{% endblock %}